### ISSUE TITLE
Incorrect use of iptables to drop attack sources

### ISSUE THREAD

**Issue by ry-ry-ry** [voidptr2x/Cyber-Shield-v4#1]
https://github.com/voidptr2x/Cyber-Shield-v4/blob/fa7e0ca38be34c484c7ba2fb7f60e227a41d66e4/protection.v#L59

There are numerous issue with the referenced code:

- First, using the INPUT chain in the filter table is not the most optimal choice when your whole objective is to mitigate DDoS attacks, which you should be trying to be high performant for.
-  You then go ahead and block the IP address in the OUTPUT chain, while still using the -s (source IP) directive of iptables. This would imply that your server would be sending traffic *from* the IP address in question. It should be moved to the -d (destination IP ) directive if you want to prevent your server from fully processing outbound traffic to the problematic IP addresses. But, if traffic is being dropped in iptables, your server shouldn't be sending responses anyway.
- iptables-save doesn't do what you think it does.

**Comment by voidptr2x** [comment]
Useless Information for Cyber Shield

**Comment by ry-ry-ry** [comment]
Useless information that you're not using iptables correctly and also inefficiently despite being a self proclaimed protection product?
