### ISSUE TITLE
Improper IPv4 Validation

### ISSUE THREAD

**Issue by ry-ry-ry** [voidptr2x/Cyber-Shield-v4#2]
https://github.com/voidptr2x/Cyber-Shield-v4/blob/fa7e0ca38be34c484c7ba2fb7f60e227a41d66e4/core/tools/connection.v#L145

The code referenced is not the correct way to validate an IPv4 address. This will fail to validate an IP with *any* octet that is zero. For example, even 127.0.0.1 would fail, because at least one of the octets is zero. This seems like something that should be done with regex instead. Perhaps with something like:

`\b(?:(?:2(?:[0-4][0-9]|5[0-5])|[0-1]?[0-9]?[0-9])\.){3}(?:(?:2([0-4][0-9]|5[0-5])|[0-1]?[0-9]?[0-9]))\b`

Unless V has something that can natively validate.

**Comment by voidptr2x** [comment]
This isnt to validate an IP. this is used for something else which was removed

**Comment by ry-ry-ry** [comment]
It clearly is to validate an IP. The function name is even called `validate_ipv4`.

And, if the feature that utilized that function no longer exists, why has this function not been removed?
