### ISSUE TITLE
Unusual file deletion practice

### ISSUE THREAD

**Issue by ry-ry-ry** [voidptr2x/Cyber-Shield-v4#3]
https://github.com/voidptr2x/Cyber-Shield-v4/blob/fa7e0ca38be34c484c7ba2fb7f60e227a41d66e4/core/tools/connection.v#L187

Does V not have any function to manipulate files? Executing a system command to delete a file seems like a strange way to do it. Also, as it's a singular file you don't need to use the -r recursive directive which would command rm to follow & delete directories as well.

From what I can tell, V has a function to remove files with `os.remove(path)`

**Comment by voidptr2x** [comment]
No need. This is an optional thing. Not an official way of doing anything

**Comment by ry-ry-ry** [comment]
You're right. Writing good code is optional.

If implementing a **very** simple change is too much for you I suppose that's your prerogative.
