### ISSUE TITLE
Vulnerable Authentication & Lack of Error Handling in app_auth 

### ISSUE THREAD

**Issue by ConservativeBaron** [voidptr2x/Cyber-Shield-v4#4]
The app_auth module is missing proper error handling, which could lead to potential security issues and unexpected behavior. To ensure the module is reliable and secure, we need to implement better error handling for the connect_to_backend and connection functions, and we should also include some sort of encryption to prevent MITM attacks.

**Comment by voidptr2x** [comment]
Its isnt missing anything at all. Main handler for it is in the main file!

**Comment by voidptr2x** [comment]
The app itself contains no personal information from users. No need for encryption
