### ISSUE TITLE
Unnecessary File Reads & Writes

### ISSUE THREAD

**Issue by ConservativeBaron** [voidptr2x/Cyber-Shield-v4#5]
The program has a load of read and write operations that i believe are unnecessary, like in `/core/tools/os.v` it reads files to get operating system information like:
```v
pub fn (mut o OS) parse_os()
{
	os_info := os.read_file("/etc/os-release") or { 
		print("[!] Error - kOeDSe5R0pz1, Unable to read file....!")
		exit(0)
	}
	for line in os_info.split("\n")
	{
		if line.starts_with("NAME=\"") { o.name = line.replace("NAME=\"", "").replace("\"", "") }
		if line.starts_with("VERSION_ID=\"") { o.version = line.replace("VERSION_ID=\"", "").replace("\"", "") }
	}
}
```
but the issue i find with this code is that you can use modules that have already been imported like os to get the same information without reading files, by doing this it will reduce the risk of errors, increase speeds by using variables that already exist and make it easier to improve compatibility with other operating systems:
```v
pub fn (mut o OS) parse_os() {
    o.name = os.name()
    o.version = os.version()
}
```

**Comment by voidptr2x** [comment]
This has no write operation && reading linux files are how most modern linux apps are done. Do some research

**Comment by ConservativeBaron** [comment]
Thank you for reaching out, you're correct this doesn't include write operations but that's because this is only an example and not all occurrences. I understand that reading files on its own isn't a bad thing but it's a waste of time when the variable already exists and can be entirely shrinked to 2 lines that make the code more readable and compatible.

**Comment by voidptr2x** [comment]
> Thank you for reaching out, you're correct this doesn't include write operations but that's because this is only an example and not all occurrences. I understand that reading files on its own isn't a bad thing but it's a waste of time when the variable already exists and can be entirely shrinked to 2 lines that make the code more readable and compatible.

False. There was bugs due to different data in /proc/cpuinfo on certain OS(s). I had no choice but to go with a loop that checks for whats needed and to avoid indexing errors
